### ISSUE TITLE
metadb for creating pyZAN server

### ISSUE THREAD

**Issue by Dhruva0707** [COPA-DATA/pyZAN#2]
Hello, I have a demo version of Zenon 8.3 on my system, on which I am running a simulation. 
![Capture](https://user-images.githubusercontent.com/37029610/123949082-c90d3900-d9bf-11eb-8531-0cd8a615b8ec.JPG)

I wish to collect data from it and subscribe to its Alarms and events. 
when I initiate the connection to the server with the command:
```zan = pyZAN.Server(server='localhost', metadb="ZA_Test")```

I get an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\Lib\site-packages\CopaData\pyZAN.py", line 59, in __init__
    + self._metadb + ";Trusted_Connection=Yes")
pyodbc.OperationalError: ('08001', '[08001] [Microsoft][SQL Server Native Client 11.0]SQL Server Network Interfaces: Error
locating Server/Instance Specified [xFFFFFFFF].  (-1) (SQLDriverConnect); [08001] [Microsoft][SQL Server Native Client 11.0]Login
timeout expired (0); [08001] [Microsoft][SQL Server Native Client 11.0]Invalid connection string attribute (0); [08001] [Microsoft
[SQL Server Native Client 11.0]A network-related or instance-specific error has occurred while establishing a connection to SQL
Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote
connections. For more information see SQL Server Books Online. (-1)')
```

This suggests that either the metadb name was incorrect or that we need to change some permissions. My questions are as follows:

1.  In the vanilla installation of Zenon, what should we use as the metadb name from pyZAN ?or if it can be set where we can set it?
2. Are there any additional permissions/configurations we have to set up before we can use pyZAN in this way?
3. Is it possible to collect events and Alarms generated by Zenon using pyZAN as it is possible from the C# library?

**Comment by CD-PSchmidt** [comment]
Hi,
it has been some time since the issue was raised. Where you able to solve it?
Are you sure, that the zenon Analyzer / Report Engine  is installed on that very same system, and that you have synchronized the projects metadata with the Report Engine?
